### ISSUE TITLE
below links are not working

### ISSUE THREAD

**Issue by bibekshhh** [Hyperce-internal-demos/zippybox-docs#3]
![image](https://github.com/Hyperce-internal-demos/zippybox-docs/assets/90471455/ccf78320-47ae-4950-b50a-b427a77bcdbe)

![image](https://github.com/Hyperce-internal-demos/zippybox-docs/assets/90471455/658d4a79-7576-4b90-aaac-93b885b1d8b4)

![image](https://github.com/Hyperce-internal-demos/zippybox-docs/assets/90471455/753a89c9-2a27-4346-91d2-4405f8dd1dfa)

![image](https://github.com/Hyperce-internal-demos/zippybox-docs/assets/90471455/b1f9ded5-d2f8-4304-aabe-6e7b63891446)
**In above image: `Tag Subscriber` page is not working**

![image](https://github.com/Hyperce-internal-demos/zippybox-docs/assets/90471455/eebac7fe-03bd-478e-ba97-6fb11946a48c)

**Comment by bini2002** [comment]
done
